swagger: '2.0'
info:
  version: '0.1'
  title: Artifact locate service (raven)
  description: 'A programmatic interface for determining the storage locations of an artifact.  Artifacts may be available at multiple storage sites.  Querying for the location of an artifact will result in a list of zero or more pre-authorized URLs that can be used for downloading the artifact.  For non-public artifacts, credentials must be supplied to gain authorization.  <br/><br/>Clients may authenticate to this service in one of two ways:<br/>1.  By providing a cookie in the Cookie header<br/>2.  By using a client certificate over SSL.'
basePath: '/raven'

paths:
  '/locate':
    post:
      description: 'Find all the download locations of a given artifact by posting a transfer request and receiving a transfer response, with pre-authorized URLs, in return.'
      tags:
        - Artifact locate
      summary: Locate an artifact
      schemes:
        - https
      consumes:
        - text/xml
      produces:
        - text/xml
      parameters:
        - name: transfer-request
          in: body
          description: 'A transfer object (according to the VOSpace 2.1 specification) containing the target artifact (Artifact URI) and direction (only pullFromVoSpace supported).'
          required: true
      responses:
        '200':
          description: 'A transfer-response object containing the transfer-request information and a list of zero or more pre-authorized download endpoint URLs.'
        '401':
          description: If the client does not provide credentials and anonymous access is disallowed.
        '403':
          description: If the client does not have permission.
        '404':
          description: If the artifact could not be found.
        '500':
          description: Internal error
        '503':
          description: Service busy
  /availability:
    get:
      tags:
        - Support Interfaces
      summary: VOSI Availability
      description: 'Indicates whether the service is operable and shows the reliability of the service for extended and scheduled requests. If the query parameter ''detail=min'' is used, a light weight heart beat test will be performed. The heart beat test returns status 200 if the service is available.'
      parameters:
        - name: detail
          in: query
          description: 'Specifies heart beat to be used to check for availability of this service, the value ''min'' must be used, otherwise the full availability test will be performed'
          required: false
          type: string
      responses:
        '200':
          description: A VOSI availability document in XML.
  /capabilities:
    get:
      summary: VOSI Capabilities
      tags:
        - Support Interfaces
      description: |
        Provides the service metadata in the form of a list of Capability descriptions.  Each of these descriptions is an XML element that:
        <ul>
        <li>states that the service provides a particular, IVOA-standard function;</li>
        <li>lists the interfaces for invoking that function;</li>
        <li>records any details of the implementation of the function that are not defined as default or constant in the standard for that function.</li>
        </ul>
      responses:
        '200':
          description: A VOSI Capabilities document in XML.
        '500':
          description: Internal server error
        '503':
          description: Service too busy
