swagger: '2.0'
info:
  version: '0.1'
  title: storage metadata query service (luskan)
  description: A programatic interface for querying the file metadata of the storage inventory system. The service uses the IVOA Table Access Protocol (TAP)
schemes:
  - http
basePath: /luskan
paths:
  /async:
    post:
      summary: TAP-1.1 asynchronous query execution end point (create UWS Job).
      tags:
        - TAP
      description: |
        TAP-1.1 async endpoint to create a new query job in the PENDING state
      parameters:
        - name: LANG
          in: query
          description: specify the query language used in the QUERY parameter
          required: true
          type: string
        - name: QUERY
          in: query
          description: specify the query
          required: true
          type: string
        - name: FORMAT
          in: query
          description: 'supported for backwards compatibility to 1.0 (see: RESPONSEFORMAT)'
          required: false
          type: string
        - name: RESPONSEFORMAT
          in: query
          description: select output table format
          required: false
          type: string
        - name: MAXREC
          in: query
          description: request a specific limit on number of rows to return
          required: false
          type: integer
          format: int64
        - name: DEST
          in: query
          description: specify destination where output should be written (VOSpace URI)
          required: false
          type: string
          format: uri
        - name: UPLOAD
          in: query
          collectionFormat: multi
          description: >-
            specify name,location pair for a table to be uploaded and used in
            the query
          required: false
          type: string
      produces:
        - text/xml
      responses:
        '200':
          description: Successful response
        '401':
          description: Unauthorized - User not authenticated
        '404':
          description: Not Found - User not found
        '500':
          description: Internal error
        '503':
          description: Service busy
        default:
          description: Unexpeced error
          schema:
            $ref: '#/definitions/Error'
  /sync:
    get:
      summary: TAP-1.1 synchronous query execution end point
      tags:
        - TAP
      description: |
        TAP-1.1 synchronous query endpoint
      parameters:
        - name: LANG
          in: query
          description: specify the query language used in the QUERY parameter
          required: true
          type: string
        - name: QUERY
          in: query
          description: specify the query
          required: true
          type: string
        - name: FORMAT
          in: query
          description: 'supported for backwards compatibility to 1.0 (see: RESPONSEFORMAT)'
          required: false
          type: string
        - name: RESPONSEFORMAT
          in: query
          description: select output table format
          required: false
          type: string
        - name: MAXREC
          in: query
          description: request a specific limit on number of rows to return
          required: false
          type: integer
          format: int64
        - name: UPLOAD
          in: query
          collectionFormat: multi
          description: >-
            specify name,location pair for a table to be uploaded and used in
            the query
          required: false
          type: string
      produces:
        - application/x-votable+/xml
      responses:
        '200':
          description: Successful response
        '401':
          description: Unauthorized - User not authenticated
        '404':
          description: Not Found - User not found
        '500':
          description: Internal error
        '503':
          description: Service busy
        default:
          description: Unexpeced error
          schema:
            $ref: '#/definitions/Error'
    post:
      summary: TAP-1.1 synchronous query execution
      tags:
        - TAP
      description: >
        TAP-1.1 synchronous query endpoint; this endpoint will redirect to a
        job-specific URL for execution
      parameters:
        - name: LANG
          in: query
          description: specify the query language used in the QUERY parameter
          required: true
          type: string
        - name: QUERY
          in: query
          description: specify the query
          required: true
          type: string
        - name: FORMAT
          in: query
          description: 'supported for backwards compatibility to 1.0 (see: RESPONSEFORMAT)'
          required: false
          type: string
        - name: RESPONSEFORMAT
          in: query
          description: select output table format
          required: false
          type: string
        - name: MAXREC
          in: query
          description: request a specific limit on number of rows to return
          required: false
          type: integer
          format: int64
        - name: UPLOAD
          in: query
          collectionFormat: multi
          description: >-
            specify name,location pair for a table to be uploaded and used in
            the query
          required: false
          type: string
      produces:
        - application/x-votable+/xml
      responses:
        '200':
          description: Successful response
        '401':
          description: Unauthorized - User not authenticated
        '404':
          description: Not Found - User not found
        '500':
          description: Internal error
        '503':
          description: Service busy
        default:
          description: Unexpeced error
          schema:
            $ref: '#/definitions/Error'
  /availability:
    get:
      tags:
        - Support Interfaces
      summary: VOSI Availability 1.0
      description: >-
        Indicates whether the service is operable and shows the reliability of
        the service for extended and scheduled requests. If the query parameter
        'detail=min' is used, a light weight heart beat test will be performed.
        The heart beat test returns status 200 if the service is available.
      parameters:
        - name: detail
          in: query
          description: >-
            specifies heart beat to be used to check for availability of this
            service, the value 'min' must be used, otherwise the full
            availability test will be performed
          required: false
          type: string
      produces:
        - text/xml
      responses:
        '200':
          description: A VOSI availability document in XML.
          schema:
            $ref: '#/definitions/availability'
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'
  /capabilities:
    get:
      summary: VOSI Capabilities 1.0
      tags:
        - Support Interfaces
      description: >
        Provides the service metadata in the form of a list of Capability
        descriptions.  Each of these descriptions is an 

        XML element that:

        <ul>

        <li>states that the service provides a particular, IVOA-standard
        function;</li>

        <li>lists the interfaces for invoking that function;</li>

        <li>records any details of the implementation of the function that are
        not defined as default or constant in the standard for that
        function.</li>

        </ul>
      produces:
        - text/xml
      responses:
        '200':
          description: A VOSI Capabilities document in XML.
          schema:
            $ref: '#/definitions/capabilities'
        '500':
          description: Internal server error
        '503':
          description: Service too busy
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'
  /tables:
    get:
      summary: VOSI Tables 1.1
      tags:
        - Support Interfaces
      description: |
        Provides the table metadata in the form of a TableSet descriptions.
      produces:
        - text/xml
      responses:
        '200':
          description: A VOSI Tables document in XML.
          schema:
            $ref: '#/definitions/tables'
        '500':
          description: Internal server error
        '503':
          description: Service too busy
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'
definitions:
  Job:
    type: string
  availability:
    type: object
    xml:
      name: availability
      namespace: 'http://www.ivoa.net/xml/VOSIAvailability/v1.0'
      prefix: vosi
    properties:
      available:
        type: boolean
        xml:
          attribute: true
          prefix: vosi
      note:
        type: string
        xml:
          attribute: true
          prefix: vosi
  tables:
    type: object
    xml:
      namespace: 'http://www.ivoa.net/xml/VOSITables/v1.1'
      prefix: vosi
    properties:
      available:
        type: boolean
        xml:
          attribute: true
          prefix: vosi
      note:
        type: string
        xml:
          attribute: true
          prefix: vosi
  capabilities:
    type: array
    items:
      $ref: '#/definitions/capability'
    xml:
      name: capability
      namespace: 'http://www.ivoa.net/xml/VOSICapabilities/v1.0'
      prefix: vosi
      wrapped: true
  capability:
    type: object
    properties:
      standardID:
        type: string
        format: uri
        xml:
          attribute: true
      interface:
        type: object
        properties:
          accessURL:
            type: string
            properties:
              use:
                type: string
                xml:
                  attribute: true
          securityMethod:
            type: string
            properties:
              standardID:
                type: string
                format: uri
                xml:
                  attribute: true
  Error:
    required:
      - code
      - message
    properties:
      code:
        type: integer
        format: int32
      message:
        type: string

