version: "3.2"
services:

  tbd:
    image: tbd:latest
    build: ./
    depends_on:
      - "haproxy"
    ports:
      - "8080:8080"
    networks:
      - "tbd-network"
    volumes:
      - "/Users/jburke/work/docker/cadc-tomcat/conf:/conf:ro"
      - "/Users/jburke/work/docker/cadc-tomcat/logs:/logs:rw"

  haproxy:
    image: cadc-haproxy-dev:latest
    ports:
      - "443:443"
    networks:
      - "tbd-network"
    volumes:
      - "/Users/jburke/work/docker/cadc-haproxy-dev/conf:/conf:ro"
      - "/Users/jburke/work/docker/cadc-tomcat/logs:/logs:rw"

networks:
  tbd-network:
