name: Docker Image CI

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build minoc
      run: cd minoc && docker build . --file Dockerfile --tag minoc:$(date +%s)
    - name: Build luskan
      run: test -d luskan && (cd luskan && docker build . --file Dockerfile --tag luskan:$(date +%s)) || echo "not found"
