name: Java CI

on: 
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Gradle
      run: cd storage-inventory-dm && gradle --info clean build && cd ..
      run: cd cadc-inventory && gradle --info clean build javadoc checkstyleMain && cd ..
      run: cd cadc-inventory-db && gradle --info clean build javadoc checkstyleMain && cd ..
      run: cd cadc-storage-adapter && gradle --info clean build javadoc checkstyleMain && cd ..
      run: cd cadc-storage-permissions && gradle --info clean build javadoc checkstyleMain && cd ..
